Operações numéricas com arrays

In [1]:
import numpy as np

Operações elemento a elemento

Com escalares:

In [5]:
a = np.array([1, 2, 3, 4])
a + 1
2**a

array([ 2,  4,  8, 16])

Todas operações aritiméticas operam elemento a elemento:
ATENÇÃO: Multiplicação de array não é multiplicação de matrizes.

In [7]:
b = np.ones(4) + 1
a - b
a * b
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [8]:
c = np.ones((3, 3))
c * c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Multiplicação de matrizes:

In [10]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

Comparações:

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b
a > b

array([False, False,  True, False])

Operações logicas:

In [13]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)
np.logical_and(a, b)

array([ True, False, False, False])

Incompatibilidade de forma:

In [14]:
a = np.arange(4)
a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Matriz Transposta

In [16]:
a = np.triu(np.ones((3, 3)), 1)   # veja help(np.triu)
a
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

<b>Reduções Básicas</b>

In [18]:
#soma
x = np.array([1, 2, 3, 4])
np.sum(x)
x.sum()

10

Soma por linha e coluna

In [19]:
x = np.array([[1, 1], [2, 2]])
x
x.sum(axis=0)   # colunas (primeira dimensão)
x[:, 0].sum(), x[:, 1].sum()
x.sum(axis=1)   # linhas (segunda dimensão)
x[0, :].sum(), x[1, :].sum()

(2, 4)

A ideia é a mesma em maiores dimensões:

In [20]:
x = np.random.rand(2, 2, 2)
x.sum(axis=2)[0, 1]     
x[0, 1, :].sum()

0.1189698455367072

Broadcasting

As operações básicas nas arrays do NumPy são elemento a elemento;
Essas operações só funcionam em arrays de mesmo tamanho, no entanto, é possível fazer operações em arrays de diferentes tamanhos se o NumPy puder transformá-las para que todas tenham o mesmo tamanho: essa convenção é chamada de Broadcasting.

In [21]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a
b = np.array([0, 1, 2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [22]:
a = np.ones((4, 5))
a[0] = 2  # atribuimos uma array de dimensão 0 a uma array de dimensão 1
a

array([[2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Broadcasting parece ser um pouco mágico, mas na verdade é bem natural utilizá-lo quando se deseja resolver um problema no qual os dados de saída são uma array com mais dimensões que os dados de entrada.

Vários problemas do tipo grid-based ou netword-bases podem também utilizar broadcasting. Por exemplo, se desejarmos calcular a distância da origem aos pontos em um grid de 10×10, podemos fazer:

In [23]:
x, y = np.arange(5), np.arange(5)
distance = np.sqrt(x ** 2 + y[:, np.newaxis] ** 2)
distance

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [4.        , 4.12310563, 4.47213595, 5.        , 5.65685425]])

Detalhe: a função numpy.pgrid permite criar diretamento vetores x e y do exemplo anterior com duas “dimensões significativas”.

In [25]:
x, y = np.ogrid[0:5, 0:5]
x, y
x.shape, y.shape
distance = np.sqrt(x ** 2 + y ** 2)

Então, o np.ogrid é muito útil quando precisarmos lidar com computação de dados em grids. Por outro lado, np.mgrid oferece matrizes cheias de índices para os casos os não quisermos ou não pudermos nos beneficiar do broadcasting:

In [26]:
x, y = np.mgrid[0:4, 0:4]
x
y

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

Manipulação de forma do array

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()
a.T
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [28]:
#remodelagem
a.shape
b = a.ravel()
b
b.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

Criando um array de forma diferente com outro array:

In [3]:
a = np.arange(36)
b = a.reshape((6, 6))
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [30]:
b = a.reshape((6, -1))

<b>Ordenando dados</b>

In [5]:
#ordenando em um eixo
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

In [6]:
a.sort(axis=1)
a

array([[3, 4, 5],
       [1, 1, 2]])