<center><h2>Numpy
</center>

NumPy é um pacote de Python que suporta operações com vetores e matrizes e é essencial para a computação científica com Python. O NumPy é baseado em C, portanto tem um desempenho superior se comparado às operações com vetores originais do Python. Neste post eu quero mostrar uma introdução básica ao NumPy para os iniciantes.

A partir de agora, vamos ver na pratica como isso funciona.

In [2]:
# importando o numpy
import numpy as np

In [2]:
# exemplo 1. O array a tem apenas uma dimensão com os valores 1, 2 e 3
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
# exemplo 1.1 Já o array b possui duas dimensões com os valores 1, 2, 3, 4, 5 e 6.
b = np.array([[1,2,3], [4,5,6]])

In [5]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# exercicio. agora quero um array de 4 dimensões, crie ele
c = np.array([[1,2,3], [4,5,6], [7,8,9], [1,2,3]] )
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [6]:
# exemplo 1.2 em alguns casos, preciso criar um array vazio de n dimensões.
array_zerado = np.zeros((3,4))

In [7]:
array_zerado

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# exemplo 1.2 - criar um array, já com seu tipo devido.
array_int = np.array([4,5], dtype=int)

In [9]:
array_int

array([4, 5])

In [14]:
# exemplo 1.3 como faço para pegar uma posição especifica do array ?
array_int[0]

4

In [18]:
# exercicio crie uma matriz bidimensiol com os seguintes valores: 4,6,8,9; pegue os valores das posições 0 e 1 e some os dois

In [20]:
# exemplo 1.4 muita das vezes eu não sei o tamanho do array, porem o numpy tem um metodo que me ajuda a entender isso.
array_zerado.shape

(3, 4)

In [21]:
# a partir dos proximos exemplo vamos ver como realizar operações matemáticas em um array.

In [22]:
# 1-) soma
b.sum()

21

In [23]:
# 2-) valor minimo
b.min()

1

In [24]:
# 3-) valor maximo
b.max()

6

In [25]:
# 4-) a media
b.mean()

3.5

In [27]:
# 5-) o desvio padrão
b.std()

1.707825127659933

In [37]:
# exemplo 1.6 inserindo um novo elemento no array e transformando em uma tupla
np.insert(b, 3,8)

array([1, 2, 3, 8, 8, 8, 4, 5, 6])

In [38]:
# exemplo 1.7 se posso inserir também quero remover
np.delete(b,[0])

array([2, 3, 8, 8, 4, 5, 6])

In [39]:
# exemplo 1.8 posso somar duas matrizes ?
m1 = np.array([1,2])
m2 = np.array([0,3])

In [46]:
v1 = np.sum(m1 + m2)

In [47]:
v1

6

In [48]:
# exemplo 1.9 o produto entre duas matrizes.
np.dot(m1, m2)

6

In [50]:
# exemplo 1.10 vendo a covariança da matriz.
np.cov(m1)

array(0.5)

Criar duas matrizes 2x3 com valores que quiser.... Fazer a soma, minimo e multiplicação das matrizes

In [44]:
m1 = np.array([[1,2], [4,5], [4,5]])
m2 = np.array([[6,7], [7,8]])
#print(np.sum(m1 + m2))
#print(np.min([m1,m2]))
print(np.dot(m1, m2))

[[20 23]
 [59 68]
 [59 68]]


In [ ]:
mx = np.array([[35,5,6,7,3,5],[35,5,6,7,3,5],[35,5,6,7,3,5],[35,5,6,7,3,5],[35,5,6,7,3,5],[35,5,6,7,3,5],[35,5,6,7,3,5],[35,5,6,7,3,5]])
mx.shape

In [3]:
def calculadora(): 
    while True: 
        try: 
            nr1 = int(input("Por favor, informe primeiro número: "))
            nr2 = int(input("Por favor, informe segundo número: ")) 
            op = input("Informe a Operação:") 
            if(op == '+' or op == 'soma'): 
                print(nr1 + nr2) 
            elif(op == '-' or op == 'subtracao'): 
                print(nr1 - nr2) 
            elif(op == '*' or op == 'multiplicacao'): 
                print(nr1 * nr2) 
            elif(op == '/' or op == 'divisao'): 
                print(nr1 / nr2) 
            elif(op == 'sair'):
                print('Bye Bye!')
                break 
            else:  
                print('Digite operacao correta')
                
        except ZeroDivisionError:
            print("Divisão por Zero não é permitida !")
        except Exception: 
            print("Valores incorretos !")
                                    

In [4]:
calculadora()

Por favor, informe primeiro número: 1
Por favor, informe segundo número: 2
Informe a Operação:sair
Bye Bye!
